language: python
python:
  - "3.8"
  - "3.8-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
